title: "Home"
author:  "Lars Nørtoft Reiter"
description: "<i>Posts about philosophy and statistics.</i>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
 - {file: "index.html", icon: home}
 # - {title: Projects, file: "projects.md"}
 - {title: About me, icon: user,  file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:lars.reiter.nielsen@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/LaReiter"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/lars-n%C3%B8rtoft-reiter-01646099/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
