title: "Lars Reiter Nielsen"
author:  "Lars Reiter Nielsen"
description: "<i>Man's greatest asset is the unsettled mind</i>"
permalink: /World of :title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: CV, file: "blog.md"}
  - {title: Blog, file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:lars.reiter.nielsen@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/LaReiter"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/lars-reiter-nielsen-01646099/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
