---
title: "U1 SS"
author: "Lars"
date: "30/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
Det her er min besvarelse af assignment 1. "ctrl" + "alt" + i giver kodefelt

# Exercise 1.1

```{r}
(v <- rep(0,6))
(w <- rep(c(0,1), each=3))
(x <- 1:5*2)
(y <- rep(1,5)*c(-1,1))
(z <- rep(2,7)^(0:6))

x+z
z[-7]
```
# Exercise 1.4

```{r}
TRUE + 1

( x <- sample(c(TRUE,FALSE),size=10,replace=T))
sum(x)>5

TRUE * TRUE
FALSE * FALSE
TRUE * FALSE
FALSE * TRUE

```

# Exercise 2.1

```{r}
( M1 <- matrix(1:12, nrow = 3) )
( M2 <- matrix(1:12, nrow = 3, byrow = TRUE) )

M1[1,1]
M2[2,]
M2[,3]


M1*M2
```

# 4.1

```{r}
(z <- 1:6)
w <- c(1,2531,2518,585,2581,51852,0)
f <- function(v) max(v)-min(v)

f(w)
```

# Exercise 2

```{r}
( a <- rep(0,20) )
( r <- rep(0,20) )
a[1] <- 0
a[2] <- 1

for (i in 3:20){
  a[i] <- a[i-1]+a[i-2]
  r[i] <- a[i]/a[i-1]
}

r
plot(1:20,r)
```

# Exercise 3

```{r}
f <- function(x){
  ifelse(x<0,0, ifelse(x>=0 & x<= 1, x^2, 2*x - 1 ))
}

f(-5)
f(1/2)
f(3)
```

# Exercise 4

```{r}
########
# Kryds og bolle
########

### DEN HER KODE HAR JEG ÆNDRET

evaluateGameState <- function(gameState){
  gm <- matrix(gameState,3,3,byrow=T)
  threeInARow <- c(colSums(gm),rowSums(gm),sum(diag(gm)),sum(diag(gm[nrow(gm):1,])))
  ifelse(-3 %in% threeInARow,-1, ifelse(3 %in% threeInARow,1, ifelse(0 %in% gm,42,0)))
}

### KODEN HEREFTER FÅR I SERVERET

showGame <- function(gameState){
  cat("\n The current game state is:\n")
  print(matrix(gameState,3,3,byrow=T))
  cat("\n")
}

playGame <- function(){
  gameState <- rep(0,9) # this line initializes the gameState to represent an empty game
  while(evaluateGameState(gameState)==42){ # while game is not over, we are doing the following:
    showGame(gameState) # this line shows the current game 
    movePlayer1 <- as.integer(readline(prompt = "Player1, please make a move: ")) # this line asks for a move by the first player
    gameState[movePlayer1] <- 1 # this line puts a '1' in the field that was chosen by the player 1
    if(evaluateGameState(gameState)==42){ # this line checks again if after the last move by player 1, the game is over
      showGame(gameState) # this line shows the current game 
      movePlayer2 <- sample(which(gameState==0),1) # computer moves at random
      gameState[movePlayer2] <- -1 # this line puts a '-1' in the field that was chosen by player 2
    }
  }
  showGame(gameState)
  cat(paste("The result is:", evaluateGameState(gameState), "\n"))
  return(evaluateGameState(gameState))
}

```

For at spille tac-tac toe skriv playGame() i konsollen efter at have kørt ovenstående kode.

